baseURL = "https://nino.work"
languageCode = "zh-cn"
title = "Nino Work"
theme = "github-style"
# googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true
summaryLength = 10

[params]
  author = "C"
  description = "In solitude, where we are least alone."
  github = "cza14h"
#  facebook = "MeiK2333"
#  twitter = "MeiK2333"
#  linkedin = "MeiK2333"
#  instagram = "MeiK2333"
#  tumblr = "MeiK2333"
  email = "ziao.chen1995@gmail.com"
  url = "https://nino.work"
  keywords = "blog, google analytics"
 # rss = true
  lastmod = true
  favicon = "/images/favicon.png"
  location = "China"
  userStatusEmoji = "😀"
  
[markup.highlight]
      codeFences = true
      guessSyntax = true
      hl_Lines = ""
      lineNoStart = 1
      lineNos = true
      lineNumbersInTable = true
      tabWidth = 2
      noClasses = false

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
